// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhsOHAWA97OHJNPkmaRZbP7vKLPk34I9Y',
    appId: '1:416737615991:web:29f85d949ac14d30c42672',
    messagingSenderId: '416737615991',
    projectId: 'expense-3a93e',
    authDomain: 'expense-3a93e.firebaseapp.com',
    storageBucket: 'expense-3a93e.appspot.com',
    measurementId: 'G-X58BLRYG23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0_22DVuVjbcYCSDtczwS2hUY8GY2Xxs',
    appId: '1:416737615991:android:e6d33ff8b71c681bc42672',
    messagingSenderId: '416737615991',
    projectId: 'expense-3a93e',
    storageBucket: 'expense-3a93e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3J8BXK8j3KQfkFYcxGiWhDq2Ujs4XHzk',
    appId: '1:416737615991:ios:82a90316ae98628fc42672',
    messagingSenderId: '416737615991',
    projectId: 'expense-3a93e',
    storageBucket: 'expense-3a93e.appspot.com',
    iosBundleId: 'com.example.expenseManageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3J8BXK8j3KQfkFYcxGiWhDq2Ujs4XHzk',
    appId: '1:416737615991:ios:82a90316ae98628fc42672',
    messagingSenderId: '416737615991',
    projectId: 'expense-3a93e',
    storageBucket: 'expense-3a93e.appspot.com',
    iosBundleId: 'com.example.expenseManageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhsOHAWA97OHJNPkmaRZbP7vKLPk34I9Y',
    appId: '1:416737615991:web:1a88546914ba8a61c42672',
    messagingSenderId: '416737615991',
    projectId: 'expense-3a93e',
    authDomain: 'expense-3a93e.firebaseapp.com',
    storageBucket: 'expense-3a93e.appspot.com',
    measurementId: 'G-C5L11QP2ET',
  );
}
